#rgs = commandArgs(trailingOnly=TRUE) 
library(doParallel)
cl <- makePSOCKcluster(50)
registerDoParallel(cl)
set.seed(12345)
library (Biostrings)
library (mnmer)

fas <- readDNAStringSet ("/labinfo/home/aandrade/data/datasets/fastas/new_mosquito_10000bp.fasta")
mntab <- mnmer (fas, 1, 2)
write.csv(mntab, file=paste0("./featureMatrix_mosquito_10000bp_12.csv"))
mntab <- mnmer (fas, 1, 3)
write.csv(mntab, file=paste0("./featureMatrix_mosquito_10000bp_13.csv"))
mntab <- mnmer (fas, 1,4)
write.csv(mntab, file=paste0("./featureMatrix_mosquito_10000bp_14.csv"))
mntab <- mnmer (fas, 2, 0)
write.csv(mntab, file=paste0("./featureMatrix_mosquito_10000bp_20.csv"))
mntab <- mnmer (fas, 3, 0)
write.csv(mntab, file=paste0("./featureMatrix_mosquito_10000bp_30.csv"))
mntab <- mnmer (fas, 4, 0)
write.csv(mntab, file=paste0("./featureMatrix_mosquito_10000bp_40.csv"))
mntab <- mnmer (fas, 5, 0)
write.csv(mntab, file=paste0("./featureMatrix_mosquito_10000bp_50.csv"))
mntab <- mnmer (fas, 2, 1)
write.csv(mntab, file=paste0("./featureMatrix_mosquito_10000bp_21.csv"))
mntab <- mnmer (fas, 2, 2)
write.csv(mntab, file=paste0("./featureMatrix_mosquito_10000bp_22.csv"))
mntab <- mnmer (fas, 2, 3)
write.csv(mntab, file=paste0("./featureMatrix_mosquito_10000bp_23.csv"))
mntab <- mnmer (fas, 3, 1)
write.csv(mntab, file=paste0("./featureMatrix_mosquito_10000bp_31.csv"))
mntab <- mnmer (fas, 3, 2)
write.csv(mntab, file=paste0("./featureMatrix_mosquito_10000bp_32.csv"))
mntab <- mnmer (fas, 4, 1)
write.csv(mntab, file=paste0("./featureMatrix_mosquito_10000bp_41.csv"))

